version: 0.0
os: linux

files:
  - source:  ./
    destination: /home/ubuntu/libs
    overwrite: yes

permissions:
  - object: /home/ubuntu/libs
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
